name: flutter_responsive_grid
description: Implementation of bootstrap concepts, like grid and display into the flutter world.
version: 0.0.1
homepage: https://github.com/GoncaloPT/flutter_responsive_grid
environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
  logging: ">=0.11.4 <1.0.0"
dev_dependencies:
  flutter_test:
    sdk: flutter
